// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbus3amw4G1lkJ0-otHDqk7GneW6IGkPE',
    appId: '1:550589088686:web:a23cf7abe3ab65bf547e3f',
    messagingSenderId: '550589088686',
    projectId: 'rentatouille-f9b6c',
    authDomain: 'rentatouille-f9b6c.firebaseapp.com',
    storageBucket: 'rentatouille-f9b6c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjSsHwxAMAKzzt2PGNjCjy1cygoiBGJd0',
    appId: '1:550589088686:android:79dee42b75c6a5fb547e3f',
    messagingSenderId: '550589088686',
    projectId: 'rentatouille-f9b6c',
    storageBucket: 'rentatouille-f9b6c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqthJbD46DyuqKr6jA0JEQfqTGWQcYHkk',
    appId: '1:550589088686:ios:092d56aff18d21c5547e3f',
    messagingSenderId: '550589088686',
    projectId: 'rentatouille-f9b6c',
    storageBucket: 'rentatouille-f9b6c.appspot.com',
    iosClientId: '550589088686-aareloq5rcr0vrgbevqal3cah4l1tpgq.apps.googleusercontent.com',
    iosBundleId: 'com.example.rentatouille',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqthJbD46DyuqKr6jA0JEQfqTGWQcYHkk',
    appId: '1:550589088686:ios:6cc303363eec7809547e3f',
    messagingSenderId: '550589088686',
    projectId: 'rentatouille-f9b6c',
    storageBucket: 'rentatouille-f9b6c.appspot.com',
    iosClientId: '550589088686-s3n6emub92ame6im99i2h0k8c6o0tmf8.apps.googleusercontent.com',
    iosBundleId: 'com.example.rentatouille.RunnerTests',
  );
}
